/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Atende;
import classes.Cliente;
import classes.Funcionario;
import classes.Venda;
import classes.Dados;
import dao.DAOAtende;
import dao.DAOCliente;
import dao.DAOFuncionario;
import dao.DAOVenda;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 0040809
 */
public class Admnistrador extends javax.swing.JDialog {

    /**
     * Creates new form Admnistrador
     */
    public Admnistrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizar();
    }
    DAOFuncionario daof = new DAOFuncionario();
    DAOCliente daoc = new DAOCliente();
    DAOVenda daov = new DAOVenda();

    /**
     * Método que atualiza as listas de consulta
     */
    public void atualizar() {
        listClie.clear();
        listFunc.clear();
        listVendas.clear();
        listClie.addAll(daoc.getLista());
        listFunc.addAll(daof.getLista());
        listVendas.addAll(daov.getLista());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listFunc = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Funcionario>());
        ;
        listClie = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Cliente>());  ;
        listVendas = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Venda>());  ;
        btgBts = new javax.swing.ButtonGroup();
        btgRbs = new javax.swing.ButtonGroup();
        configs = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        rbrS = new javax.swing.JRadioButton();
        rbrN = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        txtNomea = new javax.swing.JTextField();
        txtCpfA = new javax.swing.JTextField();
        txtEndA = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btg = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFunc = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCli = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        chkFunc = new javax.swing.JCheckBox();
        chkCli = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCpf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnAlter = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnEstoque = new javax.swing.JButton();
        btnFinanceiro = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        txtFindV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbrCli = new javax.swing.JRadioButton();
        rbrFunc = new javax.swing.JRadioButton();
        rbrId = new javax.swing.JRadioButton();
        btnFind2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnConfig = new javax.swing.JButton();

        configs.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configs.setTitle("CONFIGURAÇOES");
        configs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                configsWindowClosing(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setForeground(new java.awt.Color(255, 255, 204));

        jLabel12.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel12.setText("Configurações");

        jLabel13.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel13.setText("Senha de ADM:");

        jLabel14.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel14.setText("Usuário de ADM:");

        txtUser.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        txtSenha.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        btg.add(rbrS);
        rbrS.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        rbrS.setText("Sim");
        rbrS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbrSActionPerformed(evt);
            }
        });

        btg.add(rbrN);
        rbrN.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        rbrN.setText("Não");
        rbrN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbrNActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel15.setText("Administrador Gerente ?");

        save.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        save.setText("Salvar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        txtNomea.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtNomea.setEnabled(false);

        txtCpfA.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtCpfA.setEnabled(false);

        txtEndA.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtEndA.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel16.setText("Nome:");

        jLabel17.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel17.setText("CPF:");

        jLabel18.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel18.setText("Endereço:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(rbrS)
                                .addGap(24, 24, 24)
                                .addComponent(rbrN))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(save)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomea, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtCpfA)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(txtEndA))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbrS)
                    .addComponent(rbrN)
                    .addComponent(save))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout configsLayout = new javax.swing.GroupLayout(configs.getContentPane());
        configs.getContentPane().setLayout(configsLayout);
        configsLayout.setHorizontalGroup(
            configsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        configsLayout.setVerticalGroup(
            configsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TELA_ADMIN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 204));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        tblFunc.setBackground(new java.awt.Color(102, 102, 102));
        tblFunc.setFont(new java.awt.Font("Haettenschweiler", 0, 14)); // NOI18N
        tblFunc.setSelectionBackground(new java.awt.Color(255, 255, 153));
        tblFunc.setSelectionForeground(new java.awt.Color(0, 0, 0));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listFunc, tblFunc);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idFunc}"));
        columnBinding.setColumnName("Id Funcionario");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${CPF}"));
        columnBinding.setColumnName("CPF");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipo}"));
        columnBinding.setColumnName("Tipo");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endereco}"));
        columnBinding.setColumnName("Endereço");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblFunc);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 24, 442, 392));

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        tblCli.setBackground(new java.awt.Color(102, 102, 102));
        tblCli.setFont(new java.awt.Font("Haettenschweiler", 0, 14)); // NOI18N
        tblCli.setSelectionBackground(new java.awt.Color(255, 255, 153));
        tblCli.setSelectionForeground(new java.awt.Color(0, 0, 0));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listClie, tblCli);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idCliente}"));
        columnBinding.setColumnName("Id Cliente");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${CPF}"));
        columnBinding.setColumnName("CPF");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${data_nasc}"));
        columnBinding.setColumnName("Data nascimento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endereco}"));
        columnBinding.setColumnName("Endereço");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tblCli);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 24, 446, 392));

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel1.setText("Funcionarios");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 2, -1, -1));

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel2.setText("Clientes");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 2, -1, -1));

        btnEditar.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 457, -1, -1));

        btnExcluir.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel4.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 457, -1, -1));

        txtFind.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });
        jPanel4.add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 464, 186, -1));

        btnFind.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnFind.setText("Pesquisar");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel4.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 457, -1, -1));

        btgBts.add(chkFunc);
        chkFunc.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        chkFunc.setText("Funcionarios");
        jPanel4.add(chkFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 434, -1, -1));

        btgBts.add(chkCli);
        chkCli.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        chkCli.setText("Clientes");
        jPanel4.add(chkCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 464, -1, -1));

        jLabel3.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel3.setText("Pesquisar");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 438, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Controle", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(255, 255, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel4.setText("Cadastro de Funcionários");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 19, -1, -1));

        jLabel5.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel5.setText("Nome:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 84, -1, -1));

        txtNome.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtNome.setEnabled(false);
        jPanel5.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 106, 510, -1));

        jLabel6.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel6.setText("CPF:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 160, 42, -1));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 142, 510, 10));

        txtCpf.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtCpf.setEnabled(false);
        jPanel5.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 188, 213, -1));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 224, 213, 10));

        jLabel7.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel7.setText("Endereço:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 240, 70, -1));

        txtEnd.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtEnd.setEnabled(false);
        jPanel5.add(txtEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 268, 510, -1));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 304, 510, 10));

        cbxTipo.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Atendente", "Padeiro", "Confeiteiro", "Chef", "Empregado", "Caixa", "Entregador" }));
        cbxTipo.setEnabled(false);
        jPanel5.add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 354, 210, -1));

        jLabel8.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel8.setText("Tipo de Funcionário:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 320, 123, -1));

        btnNovo.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel5.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 142, 80, -1));

        btnSave.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSave.setText("Salvar");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 218, 80, -1));

        btnAlter.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnAlter.setText("Alterar");
        btnAlter.setEnabled(false);
        btnAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterActionPerformed(evt);
            }
        });
        jPanel5.add(btnAlter, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 180, 80, -1));

        btnCancelar.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 80, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setForeground(new java.awt.Color(255, 255, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVendas.setBackground(new java.awt.Color(102, 102, 102));
        tblVendas.setFont(new java.awt.Font("Haettenschweiler", 0, 14)); // NOI18N
        tblVendas.setForeground(new java.awt.Color(0, 0, 0));
        tblVendas.setSelectionBackground(new java.awt.Color(255, 255, 153));
        tblVendas.setSelectionForeground(new java.awt.Color(0, 0, 0));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listVendas, tblVendas);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idVenda}"));
        columnBinding.setColumnName("Id Venda");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cli}"));
        columnBinding.setColumnName("Cliente");
        columnBinding.setColumnClass(classes.Cliente.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${func}"));
        columnBinding.setColumnName("Funcionario");
        columnBinding.setColumnClass(classes.Funcionario.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pag}"));
        columnBinding.setColumnName("Pagamento");
        columnBinding.setColumnClass(classes.Pagamento.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${preco}"));
        columnBinding.setColumnName("Preço");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(tblVendas);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, 530, 455));

        jLabel9.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel9.setText("Vendas");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, -1));

        btnEstoque.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnEstoque.setText("Estoque");
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        jPanel6.add(btnEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 403, 113, -1));

        btnFinanceiro.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnFinanceiro.setText("Financeiro");
        btnFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceiroActionPerformed(evt);
            }
        });
        jPanel6.add(btnFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 359, 113, -1));

        btnRelatorio.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        jPanel6.add(btnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 315, 113, -1));

        btnNew.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnNew.setText("Novo");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel6.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 447, 113, -1));

        txtFindV.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtFindV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindVActionPerformed(evt);
            }
        });
        txtFindV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindVKeyReleased(evt);
            }
        });
        jPanel6.add(txtFindV, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 115, 207, -1));

        jLabel10.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel10.setText("Pesquisar:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 81, -1, -1));

        jLabel11.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel11.setText("Filtrar por:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 157, -1, -1));

        btgRbs.add(rbrCli);
        rbrCli.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        rbrCli.setText("Cliente");
        jPanel6.add(rbrCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 151, -1, -1));

        btgRbs.add(rbrFunc);
        rbrFunc.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        rbrFunc.setText("Funcionário");
        jPanel6.add(rbrFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 185, -1, -1));

        btgRbs.add(rbrId);
        rbrId.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        rbrId.setText("Id");
        jPanel6.add(rbrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 219, -1, -1));

        btnFind2.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnFind2.setText("Pesquisar");
        btnFind2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFind2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnFind2, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 253, -1, -1));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 293, 350, 10));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 52, 344, 10));

        btnConfig.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnConfig.setText("Configurações");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        jPanel6.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 8, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vendas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Método para atualizar tabela enquanto digita
     *
     * @param evt Evento de cada clique no teclado
     */
    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        if (evt.getKeyCode() == evt.VK_A || evt.getKeyCode() == evt.VK_B || evt.getKeyCode() == evt.VK_C || evt.getKeyCode() == evt.VK_D || evt.getKeyCode() == evt.VK_E
                || evt.getKeyCode() == evt.VK_F || evt.getKeyCode() == evt.VK_G || evt.getKeyCode() == evt.VK_H || evt.getKeyCode() == evt.VK_I || evt.getKeyCode() == evt.VK_J
                || evt.getKeyCode() == evt.VK_K || evt.getKeyCode() == evt.VK_L || evt.getKeyCode() == evt.VK_M || evt.getKeyCode() == evt.VK_N || evt.getKeyCode() == evt.VK_O
                || evt.getKeyCode() == evt.VK_P || evt.getKeyCode() == evt.VK_Q || evt.getKeyCode() == evt.VK_R || evt.getKeyCode() == evt.VK_S || evt.getKeyCode() == evt.VK_T
                || evt.getKeyCode() == evt.VK_U || evt.getKeyCode() == evt.VK_V || evt.getKeyCode() == evt.VK_X || evt.getKeyCode() == evt.VK_Y || evt.getKeyCode() == evt.VK_Z
                || evt.getKeyCode() == evt.VK_BACK_SPACE) {
            if (chkCli.isSelected()) {
                atualizarCli(txtFind.getText());
            }
            if (chkFunc.isSelected()) {
                atualizarFunc(txtFind.getText());
            }

        }
    }//GEN-LAST:event_txtFindKeyReleased
    DAOAtende daoa = new DAOAtende();
    Dados d = new Dados();

    /**
     * Método de pesquisa de um cliente ou funcionario
     *
     * @param evt
     */
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        if (chkCli.isSelected()) {
            atualizarCli(txtFind.getText());
        }
        if (chkFunc.isSelected()) {
            atualizarFunc(txtFind.getText());
        }
    }//GEN-LAST:event_btnFindActionPerformed
    /**
     * Método para excluir um cliente ou funcionário selecionado
     *
     * @param evt Evento de quando clicar no botão
     */
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        for (int i = 0; i < listClie.size(); i++) {
            if (tblCli.isRowSelected(i)) {
                int linha2 = tblCli.getSelectedRow();
                Cliente c = listClie.get(linha2);
                for (Atende atende : daoa.getLista()) {
                    if (atende.getCliente() == c.getIdCliente()) {
                        daoa.remover(atende);
                        daoc.remover(c);
                        atualizar();
                    }
                }
                daoc.remover(c);
                atualizar();
            }
        }
        for (int i = 0; i < listFunc.size(); i++) {
            if (tblFunc.isRowSelected(i)) {
                int linha = tblFunc.getSelectedRow();
                Funcionario obj = listFunc.get(linha);
                System.out.println(obj.getIdFunc());
                for (Atende atende : daoa.getLista()) {
                    if (atende.getFuncionario() == obj.getIdFunc()) {
                        daoa.remover(atende);
                    }
                }
                daof.remover(obj);
                atualizar();
            }
        }

    }//GEN-LAST:event_btnExcluirActionPerformed
    /**
     * Método para editar um cliente ou funcionário selecionado
     *
     * @param evt Evento de quando clicar no botão
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        for (int i = 0; i < listClie.size(); i++) {
            if (tblCli.isRowSelected(i)) {
                int linha2 = tblCli.getSelectedRow();
                Cliente c = listClie.get(linha2);
                FormClientes form = new FormClientes(null, true, c);
                form.setVisible(true);
                atualizar();
            }
        }
        for (int i = 0; i < listFunc.size(); i++) {
            if (tblFunc.isRowSelected(i)) {
                int linha = tblFunc.getSelectedRow();
                Funcionario obj = listFunc.get(linha);
                txtCpf.setEnabled(true);
                txtEnd.setEnabled(true);
                txtNome.setEnabled(true);
                cbxTipo.setEnabled(true);
                txtCpf.setText(obj.getCPF());
                txtEnd.setText(obj.getEndereco());
                txtNome.setText(obj.getNome());
                cbxTipo.setSelectedItem(obj.getTipo());
                btnNovo.setEnabled(false);
                btnSave.setEnabled(false);
                btnAlter.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed
    /**
     * Cria um novo funcionário
     *
     * @param evt Clique no botão
     */
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnNovo.setEnabled(false);
        btnCancelar.setEnabled(!false);
        btnSave.setEnabled(true);
        txtCpf.setEnabled(true);
        txtEnd.setEnabled(true);
        txtNome.setEnabled(true);
        cbxTipo.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed
    /**
     * Metodo que atualiza um funcionario
     *
     * @param evt Clique no botão
     */
    private void btnAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterActionPerformed
        btnNovo.setEnabled(!false);
        btnCancelar.setEnabled(false);
        btnSave.setEnabled(!true);
        btnAlter.setEnabled(false);
        int linha = tblFunc.getSelectedRow();
        Funcionario obj = listFunc.get(linha);
        obj.setCPF(txtCpf.getText());
        obj.setEndereco(txtEnd.getText());
        obj.setNome(txtNome.getText());
        obj.setTipo(cbxTipo.getSelectedItem().toString());
        if (daof.alterar(obj)) {
            JOptionPane.showMessageDialog(null, "atualizado com sucesso");

        } else {
            JOptionPane.showMessageDialog(null, "não atualizado com sucesso");
        }
        txtCpf.setText("");
        txtEnd.setText("");
        txtNome.setText("");
        cbxTipo.setSelectedItem("");
        cbxTipo.setEnabled(!true);
        txtCpf.setEnabled(!true);
        txtEnd.setEnabled(!true);
        txtNome.setEnabled(!true);
        atualizar();
    }//GEN-LAST:event_btnAlterActionPerformed
    /**
     * Metodo que salva um novo funcionario
     *
     * @param evt Clique no botão
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        btnCancelar.setEnabled(false);
        Funcionario f = new Funcionario();
        f.setCPF(txtCpf.getText());
        f.setEndereco(txtEnd.getText());
        f.setNome(txtNome.getText());
        f.setTipo(cbxTipo.getSelectedItem().toString());
        if (daof.incluir(f)) {
            JOptionPane.showMessageDialog(null, "Incluido com sucesso");

        } else {
            JOptionPane.showMessageDialog(null, "Não incluido com sucesso");
        }
        atualizar();
        txtCpf.setText("");
        txtEnd.setText("");
        txtNome.setText("");
        cbxTipo.setSelectedItem("");
        cbxTipo.setEnabled(!true);
        txtCpf.setEnabled(!true);
        txtEnd.setEnabled(!true);
        txtNome.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnSave.setEnabled(!true);
        btnAlter.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed
    /**
     * Metodo que cancela todas as ações
     *
     * @param evt Clique no botão
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtCpf.setText("");
        txtEnd.setText("");
        txtNome.setText("");
        cbxTipo.setSelectedItem("");
        cbxTipo.setEnabled(!true);
        txtCpf.setEnabled(!true);
        txtEnd.setEnabled(!true);
        txtNome.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnSave.setEnabled(!true);
        btnAlter.setEnabled(false);
        btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    /**
     * Método de pesquisa com filtros de venda
     *
     * @param evt Cada clique no teclado
     */
    private void txtFindVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindVKeyReleased
        if (evt.getKeyCode() == evt.VK_A || evt.getKeyCode() == evt.VK_B || evt.getKeyCode() == evt.VK_C || evt.getKeyCode() == evt.VK_D || evt.getKeyCode() == evt.VK_E
                || evt.getKeyCode() == evt.VK_F || evt.getKeyCode() == evt.VK_G || evt.getKeyCode() == evt.VK_H || evt.getKeyCode() == evt.VK_I || evt.getKeyCode() == evt.VK_J
                || evt.getKeyCode() == evt.VK_K || evt.getKeyCode() == evt.VK_L || evt.getKeyCode() == evt.VK_M || evt.getKeyCode() == evt.VK_N || evt.getKeyCode() == evt.VK_O
                || evt.getKeyCode() == evt.VK_P || evt.getKeyCode() == evt.VK_Q || evt.getKeyCode() == evt.VK_R || evt.getKeyCode() == evt.VK_S || evt.getKeyCode() == evt.VK_T
                || evt.getKeyCode() == evt.VK_U || evt.getKeyCode() == evt.VK_V || evt.getKeyCode() == evt.VK_X || evt.getKeyCode() == evt.VK_Y || evt.getKeyCode() == evt.VK_Z
                || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode() == evt.VK_0 || evt.getKeyCode() == evt.VK_1 || evt.getKeyCode() == evt.VK_2
                || evt.getKeyCode() == evt.VK_3 || evt.getKeyCode() == evt.VK_4 || evt.getKeyCode() == evt.VK_5 || evt.getKeyCode() == evt.VK_6
                || evt.getKeyCode() == evt.VK_7 || evt.getKeyCode() == evt.VK_8 || evt.getKeyCode() == evt.VK_9) {
            if (rbrCli.isSelected()) {
                atualizarVCli(txtFindV.getText());
            }
            if (rbrFunc.isSelected()) {
                atualizarVFunc(txtFindV.getText());
            }
            if (rbrId.isSelected()) {
                atualizarVID(txtFindV.getText());
            }

        }
    }//GEN-LAST:event_txtFindVKeyReleased
    /**
     * Método para ação de pesquisa
     *
     * @param evt Clique no botão
     */
    private void btnFind2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFind2ActionPerformed
        if (rbrCli.isSelected()) {
            atualizarVCli(txtFindV.getText());
        }
        if (rbrFunc.isSelected()) {
            atualizarVFunc(txtFindV.getText());
        }
        if (rbrId.isSelected()) {
            atualizarVID(txtFindV.getText());
        }
    }//GEN-LAST:event_btnFind2ActionPerformed
    /**
     * Método que retorna o estoque da padaria
     *
     * @param evt Clique no botão
     */
    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        Estoque e = new Estoque(null, true);
        e.setVisible(true);
    }//GEN-LAST:event_btnEstoqueActionPerformed
    /**
     * Método que gera uma nova compra
     *
     * @param evt clique no botão
     */
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        FormRealizarVendas fmrv = new FormRealizarVendas(null, true);
        fmrv.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed
    /**
     * Abre as configurações do adm
     *
     * @param evt clique no botão
     */
    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        setVisible(false);
        configs.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        configs.setSize(600, 600);
        configs.setLocation(getX() + 200, getY());
        configs.setVisible(true);
        configs.requestFocus();
    }//GEN-LAST:event_btnConfigActionPerformed
    private String user;
    private String senha;

    /**
     * Salvar o adm
     *
     * @param evt clique no botão
     */
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        user = txtUser.getText();
        senha = txtSenha.getText();
        if (rbrS.isSelected()) {
            Funcionario obj = null;
            for (Funcionario f : listFunc) {
                if (f.getTipo().equals("Gerente")) {
                    obj = f;
                }
            }
            obj.setCPF(txtCpfA.getText());
            obj.setNome(txtNomea.getText());
            obj.setEndereco(txtEndA.getText());
            obj.setTipo("Gerente");
            daof.alterar(obj);
            txtCpfA.setEnabled(!true);
            txtEndA.setEnabled(!true);
            txtNomea.setEnabled(!true);
            configs.dispose();
            try {
                d.escrever(user, senha);
                JOptionPane.showMessageDialog(null, "atualizado com sucesso");

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "não atualizado com sucesso");
                System.out.println("Erros");
            }
            setVisible(true);
        } else {
            configs.dispose();
            try {
                d.escrever(user, senha);
                JOptionPane.showMessageDialog(null, "atualizado com sucesso");
            } catch (IOException ex) {
                System.out.println("Erros");
                JOptionPane.showMessageDialog(null, "não atualizado com sucesso");
            }
            setVisible(true);
        }
    }//GEN-LAST:event_saveActionPerformed
    /**
     * Clique no botão de sim que ativa os campos
     *
     * @param evt Clique no botão
     */
    private void rbrSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbrSActionPerformed
        txtCpfA.setEnabled(true);
        txtEndA.setEnabled(true);
        txtNomea.setEnabled(true);
    }//GEN-LAST:event_rbrSActionPerformed
    /**
     * Volta a janela anterior
     *
     * @param evt clique no fechar
     */
    private void configsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_configsWindowClosing
        configs.dispose();
        setVisible(true);
    }//GEN-LAST:event_configsWindowClosing
    /**
     * Fecha os campos
     *
     * @param evt clique no botão
     */
    private void rbrNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbrNActionPerformed
        txtCpfA.setEnabled(!true);
        txtEndA.setEnabled(!true);
        txtNomea.setEnabled(!true);
    }//GEN-LAST:event_rbrNActionPerformed

    private void txtFindVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindVActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        double soma = 0;
        Date dia = new Date();
        for (Venda listVenda : listVendas) {
            soma += listVenda.getPreco();
        }
        DecimalFormat dcm = new DecimalFormat("#######.##");
        JOptionPane.showMessageDialog(null, "Relatório de Vendas \n"
                + "Total de vendas : " + listVendas.size() + "\n"
                + "Total arrecadado : " + dcm.format(soma) + "\n"
                + "Número de clientes : " + listClie.size() + "\n"
                + "Número de funcionários : " + listFunc.size() + "\n"
                + "Relatorio do dia " + dia);
    }//GEN-LAST:event_btnRelatorioActionPerformed
    /**
     * Ao fechar abre a tela principal denovo
     *
     * @param evt
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        Login obj = new Login(null, true);
        obj.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
    /**
     * Método que chama a tela do financeiro
     *
     * @param evt Clique no botão
     */
    private void btnFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceiroActionPerformed
        Financeiro f = new Financeiro(null, true);
        f.setVisible(true);
    }//GEN-LAST:event_btnFinanceiroActionPerformed

    /**
     * Método para atualizar pesquisa de dados sobre vendas com filtro de
     * clientes
     *
     * @param nome O nome do cliente como argumento
     */
    public void atualizarVCli(String nome) {
        ArrayList<Cliente> listc = new ArrayList<>();
        String word = "";
        String letra = "", letra2 = "";
        for (Cliente cliente : listClie) {
            for (int i = 0; i < nome.length(); i++) {
                letra = "" + cliente.getNome().charAt(i);
                letra2 = "" + nome.charAt(i);
                System.out.println(letra + "--" + letra2);
                if (letra.equalsIgnoreCase(letra2)) {
                    word += letra2;
                }
            }
            if (word.equals(nome)) {
                listc.add(cliente);
                System.out.println(word);
                System.out.println(nome);
                word = "";
            }
            word = "";
        }
        word = "";
        listVendas.clear();
        for (Cliente cliente : listc) {
            listVendas.addAll(daov.localizarNome("select * from venda where idCliente like '" + cliente.getIdCliente() + "';"));
        }
    }

    /**
     * Método para atualizar pesquisa de dados sobre vendas com filtro de
     * Funcionarios
     *
     * @param nome O nome do funcionario como argumento
     */
    public void atualizarVFunc(String nome) {
        ArrayList<Funcionario> listf = new ArrayList<>();
        String word = "";
        String letra = "", letra2 = "";
        for (Funcionario cliente : listFunc) {
            for (int i = 0; i < nome.length(); i++) {
                letra = "" + cliente.getNome().charAt(i);
                letra2 = "" + nome.charAt(i);
                System.out.println(letra + "--" + letra2);
                if (letra.equalsIgnoreCase(letra2)) {
                    word += letra2;
                }
            }
            if (word.equals(nome)) {
                listf.add(cliente);
                System.out.println(word);
                System.out.println(nome);
                word = "";
            }
            word = "";
        }
        word = "";
        listVendas.clear();
        for (Funcionario cliente : listf) {
            listVendas.addAll(daov.localizarNome("select * from venda where Funcionario_idFuncionario like '" + cliente.getIdFunc() + "';"));
        }
    }

    /**
     * Método para atualizar pesquisa de dados sobre vendas com filtro de ID de
     * venda
     *
     * @param nome O ID da venda como argumento
     */
    public void atualizarVID(String nome) {
        System.out.println(nome);
        if (nome.equals("")) {
            atualizar();
        } else {
            listVendas.clear();
            listVendas.addAll(daov.localizarNome("select * from venda where idVenda like '" + nome + "';"));
        }
    }

    /**
     * Método para atualizar pesquisa de dados sobre clientes
     *
     * @param nome O nome do cliente como argumento
     */
    public void atualizarCli(String nome) {
        listClie.clear();
        listClie.addAll(daoc.localizarNome("select * from cliente where nome like '" + nome + "%';"));
    }

    /**
     * Método para atualizar pesquisa de dados sobre Funcionarios
     *
     * @param nome O nome do funcionario como argumento
     */
    public void atualizarFunc(String nome) {
        listFunc.clear();
        listFunc.addAll(daof.localizarNome("select * from funcionario where nome like '" + nome + "%';"));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admnistrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admnistrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admnistrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admnistrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admnistrador dialog = new Admnistrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg;
    private javax.swing.ButtonGroup btgBts;
    private javax.swing.ButtonGroup btgRbs;
    private javax.swing.JButton btnAlter;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFind2;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JCheckBox chkCli;
    private javax.swing.JCheckBox chkFunc;
    private javax.swing.JDialog configs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.util.List<Cliente> listClie;
    private java.util.List<Funcionario> listFunc;
    private java.util.List<Venda> listVendas;
    private javax.swing.JRadioButton rbrCli;
    private javax.swing.JRadioButton rbrFunc;
    private javax.swing.JRadioButton rbrId;
    private javax.swing.JRadioButton rbrN;
    private javax.swing.JRadioButton rbrS;
    private javax.swing.JButton save;
    private javax.swing.JTable tblCli;
    private javax.swing.JTable tblFunc;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCpfA;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtEndA;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtFindV;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomea;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUser;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
