/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Cliente;
import classes.Funcionario;
import classes.Produto;
import classes.Produtos_Venda;
import classes.Produz;
import classes.Receita;
import classes.Receita_Produto;
import classes.Usa;
import classes.Venda;
import java.util.Date;
import dao.DAOAtende;
import dao.DAOCliente;
import dao.DAOFuncionario;
import dao.DAONota_Fiscal;
import dao.DAOPagamento;
import dao.DAOProdutos;
import dao.DAOProdutos_Venda;
import dao.DAOProduz;
import dao.DAOReceita;
import dao.DAOReceita_Produto;
import dao.DAOUsa;
import dao.DAOVenda;
import java.text.DecimalFormat;

/**
 *
 * @author 0040809
 */
public class Financeiro extends javax.swing.JDialog {

    /**
     * Creates new form Financeiro
     */
    public Financeiro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciar();
    }
    DAOPagamento daop = new DAOPagamento();
    DAOProdutos_Venda daopv = new DAOProdutos_Venda();
    DAOProdutos daopr = new DAOProdutos();
    DAOVenda daov = new DAOVenda();
    DAOCliente daoc = new DAOCliente();
    DAOFuncionario daof = new DAOFuncionario();
    DAOProduz daopz = new DAOProduz();
    DAOAtende daoa = new DAOAtende();
    DAONota_Fiscal daonf = new DAONota_Fiscal();
    DAOUsa daou = new DAOUsa();
    DAOReceita_Produto daorp = new DAOReceita_Produto();
    DAOReceita daor = new DAOReceita();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dispesas = new javax.swing.JLabel();
        lblGP = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblPD = new javax.swing.JLabel();
        lblNf = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        lblTT = new javax.swing.JLabel();
        lblTP = new javax.swing.JLabel();
        lblTA = new javax.swing.JLabel();
        lblpte = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Financeiro");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel1.setText("Financeiro");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dispesas.setText("Dispesas:");

        lblGP.setText("Gasto com produção:");

        lblVendedor.setText("Melhor Vendedor:");

        lblCliente.setText("Cliente mais ativo:");

        lblPD.setText("Produto mais vendido:");

        lblNf.setText("Total de notas fiscais:");

        data.setText("Data:");

        lblTT.setText("Total de Vendas:");

        lblTP.setText("Total de produtos vendidos:");

        lblTA.setText("Total arrecadado:");

        lblpte.setText("Preço total do estoque:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpte)
                    .addComponent(data)
                    .addComponent(lblNf)
                    .addComponent(lblPD)
                    .addComponent(lblCliente)
                    .addComponent(lblVendedor)
                    .addComponent(lblGP)
                    .addComponent(dispesas)
                    .addComponent(lblTA)
                    .addComponent(lblTP)
                    .addComponent(lblTT))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTT)
                .addGap(18, 18, 18)
                .addComponent(lblTP)
                .addGap(18, 18, 18)
                .addComponent(lblTA)
                .addGap(22, 22, 22)
                .addComponent(dispesas)
                .addGap(18, 18, 18)
                .addComponent(lblGP)
                .addGap(18, 18, 18)
                .addComponent(lblVendedor)
                .addGap(18, 18, 18)
                .addComponent(lblCliente)
                .addGap(18, 18, 18)
                .addComponent(lblPD)
                .addGap(18, 18, 18)
                .addComponent(lblNf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lblpte)
                .addGap(18, 18, 18)
                .addComponent(data)
                .addGap(22, 22, 22))
        );

        jLabel3.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel3.setText("PADARIA MARTINS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Financeiro dialog = new Financeiro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Método que inicia todos os labels com os dados
     */
    public void iniciar() {
        Date d = new Date();
        Cliente c = null;
        Funcionario f = null;
        int somap = 0;
        double somav = 0;
        lblTT.setText(lblTT.getText() + " " + daov.getLista().size());
        for (Produtos_Venda produtos_Venda : daopv.getLista()) {
            somap += produtos_Venda.getQuantidade();
        }
        lblTP.setText(lblTP.getText() + " " + somap);
        for (Venda venda : daov.getLista()) {
            somav += venda.getPreco();
        }
        DecimalFormat dcm = new DecimalFormat("######.##");
        lblTA.setText(lblTA.getText() + " " + dcm.format(somav));
        double dis = 0;
        for (Produto produto : daopr.getLista()) {
            for (Receita_Produto receita_Produto : daorp.getLista()) {
                if (receita_Produto.getProduto() == produto.getIdProduto()) {
                    dis += (produto.getPreco() * produto.getQuantidade());
                }
            }
        }
        double tp = 0;
        dispesas.setText(dispesas.getText() + " " + dcm.format(dis));
        for (Produz produz : daopz.getLista()) {
            for (Produto produto : daopr.getLista()) {
                if (produz.getProduto() == produto.getIdProduto()) {
                    tp += (produto.getPreco() * produto.getQuantidade());
                }
            }

        }
        lblGP.setText(lblGP.getText() + " " + dcm.format(tp));
        data.setText(data.getText() + " " + d);
        lblNf.setText(lblNf.getText() + " " + daonf.getLista().size());
        int maior = 0, qtd = 0, aux = 0;
        for (Cliente cliente : daoc.getLista()) {
            for (Venda venda : daov.getLista()) {
                if (venda.getCliente() == cliente.getIdCliente()) {
                    qtd++;
                }

            }
            if (qtd > aux) {
                maior = cliente.getIdCliente();
                aux = qtd;
            }
            qtd = 0;
        }
        for (Cliente cliente : daoc.getLista()) {
            if (maior == cliente.getIdCliente()) {
                lblCliente.setText(lblCliente.getText() + " " + cliente.getNome());
            }
        }
        qtd = 0;
        aux = 0;
        for (Funcionario func : daof.getLista()) {
            for (Venda venda : daov.getLista()) {
                if (venda.getFuncionario() == func.getIdFunc()) {
                    qtd++;
                }

            }
            if (qtd > aux) {
                maior = func.getIdFunc();
                aux = qtd;
            }
            qtd = 0;
        }
        for (Funcionario func : daof.getLista()) {
            if (maior == func.getIdFunc()) {
                lblVendedor.setText(lblVendedor.getText() + " " + func.getNome());
            }
        }
        qtd = 0;
        aux = 0;
        for (Produto produto : daopr.getLista()) {
            for (Produtos_Venda produtos_Venda : daopv.getLista()) {
                if (produtos_Venda.getProduto() == produto.getIdProduto()) {
                    qtd++;
                }
            }
            if (qtd > aux) {
                maior = produto.getIdProduto();
                aux = qtd;
            }
            qtd = 0;
        }
        double totalp = 0;
        for (Produto produto : daopr.getLista()) {
            if(maior==produto.getIdProduto()){
                lblPD.setText(lblPD.getText()+" "+produto.getNome());
            }
            totalp+=(produto.getPreco()*produto.getQuantidade());
        }
        lblpte.setText(lblpte.getText()+" "+dcm.format(totalp));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data;
    private javax.swing.JLabel dispesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblGP;
    private javax.swing.JLabel lblNf;
    private javax.swing.JLabel lblPD;
    private javax.swing.JLabel lblTA;
    private javax.swing.JLabel lblTP;
    private javax.swing.JLabel lblTT;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JLabel lblpte;
    // End of variables declaration//GEN-END:variables
}
