/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Cliente;
import classes.Nota_Fiscal;
import classes.Pagamento;
import classes.Produtos_Venda;
import classes.Venda;
import dao.DAOCliente;
import dao.DAOFuncionario;
import dao.DAONota_Fiscal;
import dao.DAOPagamento;
import dao.DAOProdutos_Venda;
import dao.DAOVenda;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Leon Jr
 */
public class FormVisualizarVendas extends javax.swing.JDialog {

    /**
     * Creates new form FormVisualizarVendas
     */
    public FormVisualizarVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizar();
    }
    DAOVenda daov = new DAOVenda();
    public void atualizar(){
        listVendas.clear();
        listVendas.addAll(daov.getLista());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listVendas = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Venda>());
        ;
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
        btnnotaFiscal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblVenda.setFont(new java.awt.Font("Haettenschweiler", 0, 14)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listVendas, tblVenda);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idVenda}"));
        columnBinding.setColumnName("Id Venda");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cli}"));
        columnBinding.setColumnName("Cliente");
        columnBinding.setColumnClass(classes.Cliente.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${func}"));
        columnBinding.setColumnName("Funcionário");
        columnBinding.setColumnClass(classes.Funcionario.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pag}"));
        columnBinding.setColumnName("Pagamento");
        columnBinding.setColumnClass(classes.Pagamento.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${preco}"));
        columnBinding.setColumnName("Preço");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblVenda);

        btnnotaFiscal.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnnotaFiscal.setText("Emitir nota fiscal 2 via");
        btnnotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotaFiscalActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Haettenschweiler", 1, 18)); // NOI18N
        jButton1.setText("Visualizar Detalhes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(btnnotaFiscal)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnotaFiscal)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que abre a visualização especifica de uma venda
     * @param evt Clique no botão de visualizar
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int linha = tblVenda.getSelectedRow();
        if(linha>=0){
        View_Venda v = new View_Venda(linha,null,true);
        v.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    Pagamento p = null;
    DAOProdutos_Venda daopv = new DAOProdutos_Venda();
    DAOPagamento daop = new DAOPagamento();
    DAOCliente daoc = new DAOCliente();
    DAOFuncionario daof = new DAOFuncionario();
    Cliente c = null;
    Venda v = null;
    DAONota_Fiscal daon = new DAONota_Fiscal();
    /**
     * Método para iniciar as variaveis com base na escolha do user
     */
    public void iniciar(){
        int linha = tblVenda.getSelectedRow();
        v = daov.getLista().get(linha);
        c = daoc.localizar(v.getCliente());
        p = daop.localizar(v.getPagamento());
    }
    /**
     * Gera a nota fiscal
     * @param evt Clique no botão
     */
    private void btnnotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotaFiscalActionPerformed
        Date d = new Date();
        iniciar();
        try {
            for (Nota_Fiscal nf : daon.getLista()) {
                System.out.println(v.getIdVenda());
                if (nf.getVenda() == v.getIdVenda()) {
                    FileWriter arq = new FileWriter("dir\\notas\\nota" + nf.getCodigo() + "n2.txt");
                    arq.write("------------------------------------------ \n"
                            + "-------------NOTA FISCAL 2----------------- \n"
                            + "Nome cliente: " + daoc.localizar(v.getCliente()) + "\n"
                            + "Nome funcionario: " + daof.localizar(v.getFuncionario()) + "\n"
                            + "Produtos : ");
                    for (Produtos_Venda produtos_Venda : daopv.getLista()) {
                        if (produtos_Venda.getVenda() == v.getIdVenda()) {
                            arq.write("" + produtos_Venda.getNome() + " qtd " + produtos_Venda.getQuantidade() + "\n");
                        }
                    }
                    DecimalFormat dcm = new DecimalFormat("#######.##");
                    arq.write("Total: " + v.getPreco() + "\n"
                            + "Troco: " + dcm.format(p.getValor()-v.getPreco()) + "\n"
                            + "Recebido " + p.getValor() + "\n"
                            + "Tipo de pagamento: "+p.getTipoPagamento()+" \n"
                            + "NOTA: " + nf.getCodigo() + "\n"
                            + "ID fiscal: " + nf.getIdNotaFiscal() + "\n"
                            + "Data: " + d + "\n"
                            + "PADARIA MARTINS CNPJ 001239494-15 \n"
                            + "Tel(33)99977-5898 padmartins@gmail.com \n"
                            + "-------------LEON SYSTEMS---------------- \n"
                            + "-----------------------------------------");
                    arq.close();
                    Runtime.getRuntime().exec("notepad dir\\notas\\nota" + nf.getCodigo() + "n2.txt");
                    Nota_Fiscal n = nf;
                    n.setCodigo(nf.getCodigo());
                    if(daon.incluir(n)){
                        JOptionPane.showMessageDialog(null,"Emitida!");
                    }else{
                        JOptionPane.showMessageDialog(null,"Erro ao emitir");
                    }
                }
            }
            
        } catch (IOException ex) {
            System.out.println("not found");
        }

    }//GEN-LAST:event_btnnotaFiscalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormVisualizarVendas dialog = new FormVisualizarVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnotaFiscal;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<Venda> listVendas;
    private javax.swing.JTable tblVenda;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
