/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.Conexao;
import java.awt.Color;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Leon Jr
 */
public class Form_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Form_Principal
     */
    public Form_Principal() {
        initComponents();
        Conexao.getConexao();
        iniciar();
        hora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBD = new javax.swing.JLabel();
        btnVenda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnProd = new javax.swing.JButton();
        horaAtual = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenuItem();
        menuForncedores = new javax.swing.JMenuItem();
        menuIngredientes = new javax.swing.JMenuItem();
        menuReceitas = new javax.swing.JMenuItem();
        menuCardapios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRealizarVendas = new javax.swing.JMenuItem();
        menuViewVendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAdmin = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Padaria Martins");
        setIconImages(null);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/padariaMartins.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel2.setText("Leon Systems");

        lblBD.setFont(new java.awt.Font("Showcard Gothic", 1, 10)); // NOI18N
        lblBD.setText("Conexão com BD: ");

        btnVenda.setForeground(new java.awt.Color(60, 63, 65));
        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vendasIcon.png"))); // NOI18N
        btnVenda.setBorder(null);
        btnVenda.setBorderPainted(false);
        btnVenda.setContentAreaFilled(false);
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setText("Realizar Venda");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setText("Produção");

        btnProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cozinharIcon.png"))); // NOI18N
        btnProd.setContentAreaFilled(false);
        btnProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)))))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblBD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(horaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblBD))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(btnVenda)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(btnProd, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addComponent(horaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Cadastros");

        menuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuClientes);

        menuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuProdutos.setText("Produtos");
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(menuProdutos);

        menuForncedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuForncedores.setText("Fornecedores");
        menuForncedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuForncedoresActionPerformed(evt);
            }
        });
        jMenu1.add(menuForncedores);

        menuIngredientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuIngredientes.setText("Ingredientes");
        menuIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngredientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuIngredientes);

        menuReceitas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuReceitas.setText("Receitas");
        menuReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReceitasActionPerformed(evt);
            }
        });
        jMenu1.add(menuReceitas);

        menuCardapios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuCardapios.setText("Cardapios");
        menuCardapios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCardapiosActionPerformed(evt);
            }
        });
        jMenu1.add(menuCardapios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vendas");

        menuRealizarVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        menuRealizarVendas.setText("Realizar Vendas");
        menuRealizarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRealizarVendasActionPerformed(evt);
            }
        });
        jMenu2.add(menuRealizarVendas);

        menuViewVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        menuViewVendas.setText("Visualizar Vendas");
        menuViewVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewVendasActionPerformed(evt);
            }
        });
        jMenu2.add(menuViewVendas);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Produção");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem1.setText("Produzir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem2.setText("Estoque");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Mais");

        menuAdmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAdmin.setText("Modo Admin");
        menuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminActionPerformed(evt);
            }
        });
        jMenu3.add(menuAdmin);

        menuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        jMenu3.add(menuSobre);

        menuFinanceiro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuFinanceiro.setText("Financeiro");
        menuFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFinanceiroActionPerformed(evt);
            }
        });
        jMenu3.add(menuFinanceiro);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método para iniciar a tela principal
     */
    public void iniciar() {
        if (Conexao.conectionState()) {
            lblBD.setText(lblBD.getText() + " Conectado");
            lblBD.setForeground(Color.green);
        } else {
            lblBD.setText(lblBD.getText() + " Desconectado");
            lblBD.setForeground(Color.red);
        }
        ImageIcon icone = new ImageIcon("./Icons/iconMartins.png");
        setIconImage(icone.getImage());
    }

    /**
     * Método que inicia a tela de Clientes
     *
     * @param evt Clique no botão do menu de cadastro
     */
    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        FormClientes form = new FormClientes(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed
    /**
     * Método que inicia a tela de Produtos
     *
     * @param evt Clique no botão do menu de cadastro
     */
    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        FormProdutos form = new FormProdutos(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuProdutosActionPerformed
    /**
     * Método que inicia a tela de Fornecedores
     *
     * @param evt Clique no botão do menu de cadastro
     */
    private void menuForncedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuForncedoresActionPerformed
        FormFornecedores form = new FormFornecedores(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuForncedoresActionPerformed
    /**
     * Método que inicia a tela de Ingredientes
     *
     * @param evt Clique no botão do menu de cadastro
     */
    private void menuIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngredientesActionPerformed
        FormIngredientes form = new FormIngredientes(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuIngredientesActionPerformed
    /**
     * Método que inicia a tela de Receitas
     *
     * @param evt Clique no botão do menu de cadastro
     */
    private void menuReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReceitasActionPerformed
        FormReceitas form = new FormReceitas(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuReceitasActionPerformed
    /**
     * Método que inicia a tela de Cardapios
     *
     * @param evt Clique no botão do menu de cadastro
     */
    private void menuCardapiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCardapiosActionPerformed
        FormCardapios form = new FormCardapios(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuCardapiosActionPerformed
    /**
     * Método que inicia a tela de realização de vendas
     *
     * @param evt Clique no botão do menu de vendas
     */
    private void menuRealizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRealizarVendasActionPerformed
        FormRealizarVendas form = new FormRealizarVendas(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuRealizarVendasActionPerformed
    /**
     * Método que inicia a tela de Visualização das vendas
     *
     * @param evt Clique no botão do menu de Vendas
     */
    private void menuViewVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewVendasActionPerformed
        FormVisualizarVendas form = new FormVisualizarVendas(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuViewVendasActionPerformed
    /**
     * Método que inicia a tela de Realizaçãp de vendas
     *
     * @param evt Clique no botão do menu principal
     */
    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        FormRealizarVendas form = new FormRealizarVendas(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnVendaActionPerformed
    /**
     * Método que inicia a tela de Produções
     *
     * @param evt Clique no botão do menu principal
     */
    private void btnProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdActionPerformed
        Form_Producao form = new Form_Producao(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnProdActionPerformed
    /**
     * Método que inicia a tela de produção
     *
     * @param evt Clique no botão do menu de produção
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Form_Producao form = new Form_Producao(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * Método que inicia a tela de Estoque
     *
     * @param evt Clique no botão do menu de produção
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Estoque form = new Estoque(null, true);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    /**
     * Método que inicia a tela do Administrador
     *
     * @param evt Clique no botão do menu de mais
     */
    private void menuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminActionPerformed
        Login log = new Login(this, true);
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuAdminActionPerformed
    /**
     * Método que inicia a tela de Financeiro
     *
     * @param evt Clique no botão do menu de mais
     */
    private void menuFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFinanceiroActionPerformed
        Financeiro obj = new Financeiro(null, true);
        obj.setVisible(true);
    }//GEN-LAST:event_menuFinanceiroActionPerformed
    /**
     * Método que inicia a tela de Sobre
     *
     * @param evt Clique no botão do menu de mais
     */
    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        JOptionPane.showMessageDialog(this, "SOFTWARE DE GESTÃO E VENDAS PARA PADARIAS \n DESENVOLVIDO POR LEON JR \n"
                + "EMAIL: JUNIOHUY2GAMER@GMAIL.COM TEL:(33)99977-5898 \n"
                + "SITE: leondvloper.freevar.com \n"
                + "TODOS OS DIREITOS RESERVADOS LEON SYSTEMS \n"
                + "Versao: 1.7.9 Build de Testes");
    }//GEN-LAST:event_menuSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Principal().setVisible(true);
            }
        });
    }

    /**
     * Método que roda uma Thread para mudar a hora da tela principal
     */
    public void hora() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        System.out.println("GAIA NA HORA");
                    }
                    horaAtual.setText("" + d);
                }
            }
        }.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProd;
    private javax.swing.JButton btnVenda;
    private javax.swing.JLabel horaAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBD;
    private javax.swing.JMenuItem menuAdmin;
    private javax.swing.JMenuItem menuCardapios;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuFinanceiro;
    private javax.swing.JMenuItem menuForncedores;
    private javax.swing.JMenuItem menuIngredientes;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menuRealizarVendas;
    private javax.swing.JMenuItem menuReceitas;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenuItem menuViewVendas;
    // End of variables declaration//GEN-END:variables
}
