/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Funcionario;
import classes.Produto;
import classes.Produz;
import classes.Receita;
import classes.Receita_Produto;
import dao.DAOFuncionario;
import dao.DAOProdutos;
import dao.DAOProduz;
import dao.DAOReceita;
import dao.DAOReceita_Produto;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Leon Jr
 */
public class Form_Producao extends javax.swing.JDialog {

    /**
     * Creates new form Form_Producao
     */
    public Form_Producao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciar();
    }
    DAOProduz daop = new DAOProduz();
    DAOReceita_Produto daorp = new DAOReceita_Produto();
    DAOFuncionario daof = new DAOFuncionario();
    DAOProdutos daopt = new DAOProdutos();
    DAOReceita daorc = new DAOReceita();

    public void atualizarProd(String nome) {
        cbxProd.removeAll();
        DefaultComboBoxModel dft = new DefaultComboBoxModel(daopt.localizarNome("select * from produto where nome like '" + nome + "%';").toArray());
        if (dft != null) {
            cbxProd.setModel(dft);
            for (Produto produto : daopt.getLista()) {
                if (produto.getNome().equals(cbxProd.getSelectedItem().toString())) {
                    txtPreco.setText("Preço para produzir o produto: R$ " + produto.getPreco());
                }
            }
        }

    }

    /**
     * Método que atualiza o combobox de receitas
     *
     * @param nome Cada nome digitado no campo de texto
     */
    public void atualizarReceita(String nome) {
        cbxReceita.removeAll();
        DefaultComboBoxModel dft = new DefaultComboBoxModel(daorc.localizarNome("select * from receita where nome like 'Receita de " + nome + "%';").toArray());
        if (dft != null) {
            cbxReceita.setModel(dft);
        }
    }

    /**
     * Método que inicia as variaveis, comboboxes
     */
    public void iniciar() {
        cbxReceita.removeAll();
        DefaultComboBoxModel dft = new DefaultComboBoxModel(daorc.getLista().toArray());
        if (dft != null) {
            cbxReceita.setModel(dft);
        }
        cbxProd.removeAll();
        DefaultComboBoxModel dft2 = new DefaultComboBoxModel(daopt.getLista().toArray());
        if (dft2 != null) {
            cbxProd.setModel(dft2);
        }
        cbxFunc.removeAll();
        DefaultComboBoxModel dft3 = new DefaultComboBoxModel(daof.getLista().toArray());
        if (dft3 != null) {
            cbxFunc.setModel(dft3);
        }

        listFuncionarios.clear();
        listProdutos.clear();
        listReceitas.clear();
        listFuncionarios.addAll(daof.getLista());
        listProdutos.addAll(daopt.getLista());
        listReceitas.addAll(daorc.getLista());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listFuncionarios = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Funcionario>());
 ;
        listProdutos = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Produto>());  ;
        listReceitas = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList< Receita>());
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        btnProduzir = new javax.swing.JButton();
        btnNewReceita = new javax.swing.JButton();
        btnNewProd = new javax.swing.JButton();
        cbxFunc = new javax.swing.JComboBox<>();
        cbxProd = new javax.swing.JComboBox<>();
        cbxReceita = new javax.swing.JComboBox<>();
        txtProd = new javax.swing.JTextField();
        txtReceita = new javax.swing.JTextField();
        spnQtd = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de produção");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel1.setText("Tela de produção");

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel2.setText("Escolha o funcionário:");

        jLabel3.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel3.setText("Escolha o produto que vai ser feito:");

        jLabel4.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel4.setText("Escolha uma receita usada para fazer o produto:");

        jLabel5.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel5.setText("Escolha a quantidade que vai ser produzida:");

        txtTotal.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtTotal.setText("Total gasto na produção:");

        txtPreco.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtPreco.setText("Preço para produzir o produto: R$");

        btnProduzir.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnProduzir.setText("Produzir");
        btnProduzir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduzirActionPerformed(evt);
            }
        });

        btnNewReceita.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnNewReceita.setText("Nova Receita");
        btnNewReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewReceitaActionPerformed(evt);
            }
        });

        btnNewProd.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnNewProd.setText("Novo Produto");
        btnNewProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProdActionPerformed(evt);
            }
        });

        cbxFunc.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        cbxProd.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        cbxProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProdActionPerformed(evt);
            }
        });

        cbxReceita.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        txtProd.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdKeyReleased(evt);
            }
        });

        txtReceita.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtReceita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReceitaKeyReleased(evt);
            }
        });

        spnQtd.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        spnQtd.setModel(new javax.swing.SpinnerNumberModel());
        spnQtd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQtdStateChanged(evt);
            }
        });

        btnEstoque.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnEstoque.setText("Estoque");
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPreco)
                    .addComponent(txtTotal))
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProduzir)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtProd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxProd, javax.swing.GroupLayout.Alignment.LEADING, 0, 198, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNewProd))
                            .addComponent(txtReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNewReceita))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(cbxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(btnEstoque)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPreco)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal)))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewProd))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewReceita))
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnEstoque))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduzir)
                    .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Inicia a tela de cadastro de produtos
     *
     * @param evt Clique no botão de novo
     */
    private void btnNewProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProdActionPerformed
        FormProdutos form = new FormProdutos(null, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnNewProdActionPerformed
    /**
     * Método que inicia a tela de cadastro de receitas
     *
     * @param evt Clique no botão novo
     */
    private void btnNewReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewReceitaActionPerformed
        FormReceitas form = new FormReceitas(null, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnNewReceitaActionPerformed
    /**
     * Método que atualiza o combobox enquanto digita algo
     *
     * @param evt Cada letra digitada
     */
    private void txtProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdKeyReleased
        if (evt.getKeyCode() == evt.VK_A || evt.getKeyCode() == evt.VK_B || evt.getKeyCode() == evt.VK_C || evt.getKeyCode() == evt.VK_D || evt.getKeyCode() == evt.VK_E
                || evt.getKeyCode() == evt.VK_F || evt.getKeyCode() == evt.VK_G || evt.getKeyCode() == evt.VK_H || evt.getKeyCode() == evt.VK_I || evt.getKeyCode() == evt.VK_J
                || evt.getKeyCode() == evt.VK_K || evt.getKeyCode() == evt.VK_L || evt.getKeyCode() == evt.VK_M || evt.getKeyCode() == evt.VK_N || evt.getKeyCode() == evt.VK_O
                || evt.getKeyCode() == evt.VK_P || evt.getKeyCode() == evt.VK_Q || evt.getKeyCode() == evt.VK_R || evt.getKeyCode() == evt.VK_S || evt.getKeyCode() == evt.VK_T
                || evt.getKeyCode() == evt.VK_U || evt.getKeyCode() == evt.VK_V || evt.getKeyCode() == evt.VK_X || evt.getKeyCode() == evt.VK_Y || evt.getKeyCode() == evt.VK_Z
                || evt.getKeyCode() == evt.VK_BACK_SPACE) {
            atualizarProd(txtProd.getText());
        }
    }//GEN-LAST:event_txtProdKeyReleased
    /**
     * Método que atualiza o combobox enquanto digita algo
     *
     * @param evt Cada letra digitada
     */
    private void txtReceitaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReceitaKeyReleased
        if (evt.getKeyCode() == evt.VK_A || evt.getKeyCode() == evt.VK_B || evt.getKeyCode() == evt.VK_C || evt.getKeyCode() == evt.VK_D || evt.getKeyCode() == evt.VK_E
                || evt.getKeyCode() == evt.VK_F || evt.getKeyCode() == evt.VK_G || evt.getKeyCode() == evt.VK_H || evt.getKeyCode() == evt.VK_I || evt.getKeyCode() == evt.VK_J
                || evt.getKeyCode() == evt.VK_K || evt.getKeyCode() == evt.VK_L || evt.getKeyCode() == evt.VK_M || evt.getKeyCode() == evt.VK_N || evt.getKeyCode() == evt.VK_O
                || evt.getKeyCode() == evt.VK_P || evt.getKeyCode() == evt.VK_Q || evt.getKeyCode() == evt.VK_R || evt.getKeyCode() == evt.VK_S || evt.getKeyCode() == evt.VK_T
                || evt.getKeyCode() == evt.VK_U || evt.getKeyCode() == evt.VK_V || evt.getKeyCode() == evt.VK_X || evt.getKeyCode() == evt.VK_Y || evt.getKeyCode() == evt.VK_Z
                || evt.getKeyCode() == evt.VK_BACK_SPACE) {
            atualizarReceita(txtReceita.getText());
        }
    }//GEN-LAST:event_txtReceitaKeyReleased
    /**
     * Método que inicia a tela de estoque
     *
     * @param evt Clique no botao estoque
     */
    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        Estoque form = new Estoque(null, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnEstoqueActionPerformed
    /**
     * Método que salva no banco de dados os produtos produzidos
     *
     * @param evt Clique no botão produzir
     */
    private void btnProduzirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduzirActionPerformed
        Produz obj = new Produz();
        Produto p = null;
        Funcionario f = null;
        Receita r = null;
        try{
        for (Produto listProduto : listProdutos) {
            if (listProduto.getNome().equals(cbxProd.getSelectedItem().toString())) {
                p = listProduto;
            }
        }
        for (Funcionario listFunc : listFuncionarios) {
            if (listFunc.getNome().equals(cbxFunc.getSelectedItem().toString())) {
                f = listFunc;
            }
        }
        obj.setFuncionario(f.getIdFunc());
        obj.setProduto(p.getIdProduto());
        daop.incluir(obj);
        for (Receita listReceita : listReceitas) {
            if (listReceita.getNome().equals(cbxReceita.getSelectedItem().toString())) {
                r = listReceita;
            }
        }
        Receita_Produto rp = new Receita_Produto();
        rp.setProduto(p.getIdProduto());
        rp.setReceita(r.getIdReceita());
        daorp.incluir(rp);
        for (Produto produto : daopt.getLista()) {
            if (produto.getNome().equals(p.getNome())) {
                produto.setQuantidade(produto.getQuantidade() + Integer.parseInt(spnQtd.getValue().toString()));
                daopt.alterar(produto);
            }
        }
            JOptionPane.showMessageDialog(null,"Produzido com sucesso");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Não produzido");
        }
        txtPreco.setText("Preço para produzir o produto: R$");
        txtTotal.setText("Total gasto na produção:");
        txtReceita.setText("");
        txtProd.setText("");
        spnQtd.setValue(0);
        iniciar();
    }//GEN-LAST:event_btnProduzirActionPerformed
    /**
     * Método que atualiza o preço do produto escolhido
     *
     * @param evt Escolha de algo no combobox
     */
    private void cbxProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProdActionPerformed
        for (Produto produto : daopt.getLista()) {
            if (produto.getNome().equals(cbxProd.getSelectedItem().toString())) {
                txtPreco.setText("Preço para produzir o produto: R$ " + produto.getPreco());
            }
        }
    }//GEN-LAST:event_cbxProdActionPerformed
    /**
     * Método que atualiza o preço total da produção
     *
     * @param evt Escolha da quantidade no spinner
     */
    private void spnQtdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQtdStateChanged
        DecimalFormat dcm = new DecimalFormat("#######.##");
        for (Produto produto : daopt.getLista()) {
            if (produto.getNome().equals(cbxProd.getSelectedItem().toString())) {
                txtTotal.setText("Total gasto na produção: R$ " + dcm.format(((double) produto.getPreco() * Integer.parseInt(spnQtd.getValue().toString()))));
            }
        }
    }//GEN-LAST:event_spnQtdStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Producao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Producao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Producao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Producao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Producao dialog = new Form_Producao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnNewProd;
    private javax.swing.JButton btnNewReceita;
    private javax.swing.JButton btnProduzir;
    private javax.swing.JComboBox<String> cbxFunc;
    private javax.swing.JComboBox<String> cbxProd;
    private javax.swing.JComboBox<String> cbxReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private java.util.List<Funcionario> listFuncionarios;
    private java.util.List<Produto> listProdutos;
    private java.util.List<Receita> listReceitas;
    private javax.swing.JSpinner spnQtd;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JTextField txtProd;
    private javax.swing.JTextField txtReceita;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
