/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author Leon Jr
 */
import classes.Cliente;
import classes.Funcionario;
import classes.Nota_Fiscal;
import classes.Pagamento;
import classes.Produtos_Venda;
import dao.DAOPagamento;
import dao.DAOProdutos_Venda;
import dao.DAOVenda;
import classes.Venda;
import dao.DAOCliente;
import dao.DAOFuncionario;
import dao.DAONota_Fiscal;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Date;

public class Tela_Venda extends javax.swing.JDialog {

    /**
     * Creates new form Tela_Venda
     */
    public Tela_Venda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciar();
    }
    private File f;
    Cliente c = null;
    Venda v = null;
    DAONota_Fiscal daon = new DAONota_Fiscal();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProd = new javax.swing.JLabel();
        txtCli = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtRecebido = new javax.swing.JLabel();
        txtTroco = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        btnNota = new javax.swing.JButton();
        txtTipo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFunc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RESUMO VENDA");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel1.setText("Venda Concluída");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 17, -1, -1));

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel3.setText("Produtos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtProd.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jPanel1.add(txtProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 580, 30));

        txtCli.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jPanel1.add(txtCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 37, 234, 22));

        txtTotal.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtTotal.setText("Total:");
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 221, -1, -1));

        txtRecebido.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtRecebido.setText("Recebido:");
        jPanel1.add(txtRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtTroco.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtTroco.setText("Troco:");
        jPanel1.add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        btnFinalizar.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        btnNota.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnNota.setText("Emitir Nota Fiscal");
        btnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaActionPerformed(evt);
            }
        });
        jPanel1.add(btnNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        txtTipo.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtTipo.setText("Tipo:");
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel8.setText("Funcionario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        txtFunc.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jPanel1.add(txtFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 147, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que finaliza a tela
     * @param evt Clique no botão de finalizar
     */
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        dispose();
    }//GEN-LAST:event_btnFinalizarActionPerformed
    /**
     * Método que gera nota fiscal
     *
     * @param evt Clique no botão
     */
    private void btnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaActionPerformed
        Date d = new Date();
        try {
            for (Nota_Fiscal nf : daon.getLista()) {
                if (nf.getVenda() == v.getIdVenda()) {
                    FileWriter arq = new FileWriter("dir\\notas\\nota" + nf.getCodigo() + ".txt");
                    arq.write("----------------------------------------- \n"
                            + "-------------NOTA FISCAL----------------- \n"
                            + "Nome cliente: " + daoc.localizar(v.getCliente()) + "\n"
                            + "Nome funcionario: " + daof.localizar(v.getFuncionario()) + "\n"
                            + "Produtos : ");
                    for (Produtos_Venda produtos_Venda : daopv.getLista()) {
                        if (produtos_Venda.getVenda() == v.getIdVenda()) {
                            arq.write("" + produtos_Venda.getNome() + " qtd " + produtos_Venda.getQuantidade() + "\n");
                        }
                    }
                    DecimalFormat dcm = new DecimalFormat("#######.##");
                    arq.write("Total: " + v.getPreco() + "\n"
                            + "Troco: " + dcm.format(conta) + "\n"
                            + "Recebido " + FormRealizarVendas.recebido + "\n"
                            + "Tipo de pagamento: "+p.getTipoPagamento()+" \n"
                            + "NOTA: " + nf.getCodigo() + "\n"
                            + "ID fiscal: " + nf.getIdNotaFiscal() + "\n"
                            + "Data: " + d + "\n"
                            + "PADARIA MARTINS CNPJ 001239494-15 \n"
                            + "Tel(33)99977-5898 padmartins@gmail.com \n"
                            + "-------------LEON SYSTEMS--------------- \n"
                            + "----------------------------------------");
                    arq.close();
                    Runtime.getRuntime().exec("notepad dir\\notas\\nota" + nf.getCodigo() + ".txt");
                }
            }
        } catch (IOException ex) {
            System.out.println("not found");
        }

    }//GEN-LAST:event_btnNotaActionPerformed

    Pagamento p;
    DAOProdutos_Venda daopv = new DAOProdutos_Venda();
    DAOVenda daov = new DAOVenda();
    DAOPagamento daop = new DAOPagamento();
    DAOCliente daoc = new DAOCliente();
    DAOFuncionario daof = new DAOFuncionario();
    float conta;
    /**
     * Método que inicia a tela de visualização da venda
     */
    public void iniciar() {
        v = daov.getLista().get(daov.getLista().size() - 1);

        for (Cliente cliente : daoc.getLista()) {
            if (v.getCliente() == cliente.getIdCliente()) {
                c = cliente;
            }
        }
        txtCli.setText(c.getNome());
        txtTotal.setText(txtTotal.getText() + " R$ " + v.getPreco());
        txtRecebido.setText(txtRecebido.getText() + " R$ " + FormRealizarVendas.recebido);
        conta = (FormRealizarVendas.recebido - v.getPreco());
        DecimalFormat dcm = new DecimalFormat("#######.##");
        txtTroco.setText(txtTroco.getText() + " R$ " + dcm.format(conta));
        Funcionario f = null;
        for (Funcionario funcionario : daof.getLista()) {
            if (v.getFuncionario() == funcionario.getIdFunc()) {
                f = funcionario;
            }
        }
        txtFunc.setText(f.getNome());
        p = null;
        for (Pagamento pagamento : daop.getLista()) {
            if (v.getPagamento() == pagamento.getIdPagamento()) {
                p = pagamento;
            }
        }
        txtTipo.setText(txtTipo.getText() + "\n" + p.getTipoPagamento());
        for (Produtos_Venda produtos_Venda : daopv.getLista()) {
            if (produtos_Venda.getVenda() == v.getIdVenda()) {
                txtProd.setText(txtProd.getText() + " " + produtos_Venda.getNome());
            }
        }

    }
    /**
     * Método principal da classe
     * @param args 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tela_Venda dialog = new Tela_Venda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCli;
    private javax.swing.JLabel txtFunc;
    private javax.swing.JLabel txtProd;
    private javax.swing.JLabel txtRecebido;
    private javax.swing.JLabel txtTipo;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtTroco;
    // End of variables declaration//GEN-END:variables
}
