/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Cliente;
import classes.Funcionario;
import classes.Nota_Fiscal;
import classes.Pagamento;
import classes.Produto;
import classes.Produtos_Venda;
import classes.Venda;
import dao.DAOCliente;
import dao.DAOFuncionario;
import dao.DAOPagamento;
import dao.DAOProdutos;
import dao.DAOProdutos_Venda;
import dao.DAOVenda;
import dao.DAONota_Fiscal;

/**
 *
 * @author Leon Jr
 */
public class View_Venda extends javax.swing.JDialog {

    /**
     * Creates new form View_Venda
     */
    public View_Venda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    int linha;

    public int getLinha() {
        return linha;
    }

    public void setLinha(int linha) {
        this.linha = linha;
    }

    public View_Venda(int linha, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLinha(linha);
        iniciar();

    }
    DAOVenda daov = new DAOVenda();
    DAOProdutos_Venda daopv = new DAOProdutos_Venda();
    DAOPagamento daop = new DAOPagamento();
    DAOCliente daoc = new DAOCliente();
    DAOFuncionario daof = new DAOFuncionario();
    DAOProdutos daopt = new DAOProdutos();
    DAONota_Fiscal daont = new DAONota_Fiscal();

    /**
     * Método que inicia as variaveis e as listas
     */
    public void iniciar() {
        Venda v = daov.getLista().get(linha);
        lblVenda.setText(lblVenda.getText() + " " + v.getIdVenda());
        lblPreco.setText(lblPreco.getText() + " " + v.getPreco());
        for (Cliente cliente : daoc.getLista()) {
            if (cliente.getIdCliente() == v.getCliente()) {
                lblCliente.setText(lblCliente.getText() + " " + cliente.getNome());
            }
        }
        for (Funcionario funcionario : daof.getLista()) {
            if (v.getFuncionario() == funcionario.getIdFunc()) {
                lblFunc.setText(lblFunc.getText() + " " + funcionario.getNome());
            }
        }
        for (Pagamento pagamento : daop.getLista()) {
            if (v.getPagamento() == pagamento.getIdPagamento()) {
                lblPag.setText(lblPag.getText() + " " + pagamento.getTipoPagamento());
            }
        }
        for (Produtos_Venda produtos_Venda : daopv.getLista()) {
            if (produtos_Venda.getVenda() == v.getIdVenda()) {
                lblData.setText(" Data: " + produtos_Venda.getData());
                int cont = 0;
                for (Produto prod : daopt.getLista()) {
                    if (prod.getIdProduto() == produtos_Venda.getProduto()) {
                        System.out.println("enter");
                        atxProd.setEditable(false);
                        atxProd.setText(atxProd.getText() + "\n" + prod.getNome() + " qtd " + produtos_Venda.getQuantidade());

                    }
                }
            }
        }
        for (Nota_Fiscal nota_Fiscal : daont.getLista()) {
            if (nota_Fiscal.getVenda() == v.getIdVenda()) {
                lblID.setText(lblID.getText() + " " + nota_Fiscal.getIdNotaFiscal());
                lblCodigo.setText(lblCodigo.getText() + " " + nota_Fiscal.getCodigo());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblVenda = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblFunc = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblProd = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblPag = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxProd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes da Venda");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel1.setText("Detalhes de Venda");

        lblVenda.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblVenda.setText("Venda:");

        lblPreco.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblPreco.setText("Preço:");

        lblCliente.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblCliente.setText("Cliente:");

        lblFunc.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblFunc.setText("Funcionario:");

        lblCodigo.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblCodigo.setText("Código da nota:");

        lblProd.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblProd.setText("Produtos vendidos e sua quantidade vendida:");

        lblData.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblData.setText("Data:");

        lblPag.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblPag.setText("Tipo de Pagamento:");

        lblID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblID.setText("ID Nota:");

        atxProd.setColumns(20);
        atxProd.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        atxProd.setRows(5);
        jScrollPane1.setViewportView(atxProd);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVenda)
                            .addComponent(lblPreco)
                            .addComponent(lblProd)
                            .addComponent(lblCodigo)
                            .addComponent(lblFunc)
                            .addComponent(lblCliente)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(lblPag)
                            .addComponent(lblID))
                        .addGap(146, 146, 146))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblVenda)
                        .addGap(18, 18, 18)
                        .addComponent(lblPreco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblData)
                        .addGap(18, 18, 18)
                        .addComponent(lblPag)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCliente)
                    .addComponent(lblID))
                .addGap(18, 18, 18)
                .addComponent(lblFunc)
                .addGap(18, 18, 18)
                .addComponent(lblCodigo)
                .addGap(18, 18, 18)
                .addComponent(lblProd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View_Venda dialog = new View_Venda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFunc;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPag;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProd;
    private javax.swing.JLabel lblVenda;
    // End of variables declaration//GEN-END:variables
}
